# Generated by Django 2.2.4 on 2019-12-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190807_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_events',
            field=models.ManyToManyField(blank=True, related_name='users_who_saved', to='api.Event'),
        ),
    ]
