# Generated by Django 2.2.4 on 2020-01-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='distancia',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='variables',
            name='magnetismo',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='variables',
            name='obstaculos',
            field=models.IntegerField(default=None),
        ),
    ]
